#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.1 effective-5.10 (swiftlang-6.3.1.1.2 clang-2100.0.123.102)
#ifndef AIRECBLEKIT_SWIFT_H
#define AIRECBLEKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIRECBleKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import CoreBluetooth;
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIRECBleKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_ENUM_FWD_DECL(NSInteger, AIRECAudioPlayerState)
@class NSString;
@protocol AIRECAudioPlayerDelegate;
/// AIREC 音频播放器（单例）
/// 封装所有音频格式处理，对外只暴露 play/stop/pause/seek 接口
SWIFT_CLASS("_TtC11AIRECBleKit16AIRECAudioPlayer")
@interface AIRECAudioPlayer : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIRECAudioPlayer * _Nonnull shared;)
+ (AIRECAudioPlayer * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 播放状态回调
@property (nonatomic, copy) void (^ _Nullable onStateChanged)(enum AIRECAudioPlayerState);
/// 进度回调 (current, total)
@property (nonatomic, copy) void (^ _Nullable onProgress)(NSTimeInterval, NSTimeInterval);
/// 播放完成回调
@property (nonatomic, copy) void (^ _Nullable onFinished)(BOOL);
/// 错误回调
@property (nonatomic, copy) void (^ _Nullable onError)(NSString * _Nonnull);
/// delegate（优先于闭包回调）
@property (nonatomic, weak) id <AIRECAudioPlayerDelegate> _Nullable delegate;
@property (nonatomic, readonly, copy) NSString * _Nonnull currentPath;
@property (nonatomic) enum AIRECAudioPlayerState state;
@property (nonatomic, readonly) BOOL isPlaying;
@property (nonatomic, readonly) NSTimeInterval currentTime;
@property (nonatomic, readonly) NSTimeInterval duration;
/// 播放本地文件（自动处理 ATW/KA/OGG 所有格式）
/// \param path 本地文件完整路径（下载后的原始路径，ATW/KA/OGG 均支持）
///
/// \param completion 播放结果回调 (success, message)
///
- (void)playFile:(NSString * _Nonnull)path completion:(void (^ _Nullable)(BOOL, NSString * _Nonnull))completion;
/// 停止播放
- (void)stop;
/// 暂停
- (void)pause;
/// 恢复
- (void)resume;
/// 跳转
- (void)seekTo:(NSTimeInterval)time;
- (void)observeValueForKeyPath:(NSString * _Nullable)kp ofObject:(id _Nullable)obj change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
@end

SWIFT_PROTOCOL("_TtP11AIRECBleKit24AIRECAudioPlayerDelegate_")
@protocol AIRECAudioPlayerDelegate
- (void)audioPlayer:(AIRECAudioPlayer * _Nonnull)player didChangeState:(enum AIRECAudioPlayerState)state;
- (void)audioPlayer:(AIRECAudioPlayer * _Nonnull)player didUpdateProgress:(NSTimeInterval)current total:(NSTimeInterval)total;
- (void)audioPlayer:(AIRECAudioPlayer * _Nonnull)player didFinishPlaying:(BOOL)successfully;
- (void)audioPlayer:(AIRECAudioPlayer * _Nonnull)player didFailWithError:(NSString * _Nonnull)error;
@end

typedef SWIFT_ENUM(NSInteger, AIRECAudioPlayerState, open) {
  AIRECAudioPlayerStateIdle = 0,
  AIRECAudioPlayerStateLoading = 1,
  AIRECAudioPlayerStatePlaying = 2,
  AIRECAudioPlayerStatePaused = 3,
  AIRECAudioPlayerStateFinished = 4,
  AIRECAudioPlayerStateFailed = 5,
};

/// 对外公开的设备模型，不暴露任何 CoreBluetooth 类型
SWIFT_CLASS("_TtC11AIRECBleKit14AIRECBleDevice")
@interface AIRECBleDevice : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly) NSInteger rssi;
@property (nonatomic) NSInteger battery;
@property (nonatomic) int64_t storageUsed;
@property (nonatomic) int64_t storageTotal;
@property (nonatomic, copy) NSString * _Nonnull firmwareVersion;
@property (nonatomic) BOOL isRecording;
@property (nonatomic) BOOL isCharging;
@property (nonatomic) int64_t recordDuration;
@property (nonatomic, readonly, copy) NSString * _Nonnull storageStr;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 对外公开的音频文件模型
SWIFT_CLASS("_TtC11AIRECBleKit12AIRECBleFile")
@interface AIRECBleFile : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fileName;
@property (nonatomic, readonly) int64_t fileSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull createTime;
@property (nonatomic) NSInteger durationSec;
@property (nonatomic, readonly, copy) NSString * _Nonnull fileSizeStr;
@property (nonatomic, readonly, copy) NSString * _Nonnull durationStr;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// AIREC BLE 管理器（单例）
/// 对外只暴露业务级 API，所有协议细节均封装在内部
SWIFT_CLASS("_TtC11AIRECBleKit15AIRECBleManager")
@interface AIRECBleManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIRECBleManager * _Nonnull shared;)
+ (AIRECBleManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic) BOOL ledSwitch;
@property (nonatomic) BOOL noiseSwitch;
@property (nonatomic) BOOL usbSwitch;
@property (nonatomic) BOOL powerOnRecord;
@property (nonatomic) BOOL diskFormatSupport;
@property (nonatomic) NSInteger segmentDuration;
@property (nonatomic) NSInteger idleShutdown;
@property (nonatomic) NSInteger micGain;
@property (nonatomic, copy) NSString * _Nonnull macAddress;
/// 初始化 BLE 中心管理器，在 AppDelegate 中调用一次
- (void)setup;
/// 当前是否已连接设备
@property (nonatomic, readonly) BOOL isConnected;
/// 当前连接的设备（未连接时为 nil）
- (AIRECBleDevice * _Nullable)getConnectedDevice SWIFT_WARN_UNUSED_RESULT;
/// 开始扫描所有 BLE 设备
- (void)startScan;
/// 停止扫描
- (void)stopScan;
/// 连接指定设备
- (void)connect:(AIRECBleDevice * _Nonnull)device;
/// 主动断开连接
- (void)disconnect;
/// 查询电量、录音状态、存储空间
- (void)fetchDeviceInfo;
/// 连接成功后的完整初始化查询（串行，每条间隔 600ms）
/// AIREC(BLE) 无法处理同时到来的多条指令，必须逐条发送
- (void)fetchAllDeviceInfo;
/// 恢复录音（暂停后继续，发 pauseRecord toggle 0x10）
- (void)resumeRecord;
/// 查询固件版本
- (void)fetchFirmwareVersion;
/// 查询设备文件列表
- (void)fetchFileList;
/// 删除设备上的文件
- (void)deleteFile:(NSString * _Nonnull)fileName;
/// 开始录音
- (void)startRecord;
/// 暂停录音
- (void)pauseRecord;
/// 结束并保存录音
- (void)endRecord;
/// 查询设备初始化参数
- (void)fetchInitParam;
/// 设置 LED 指示灯开关
- (void)sendLedSwitch:(BOOL)on;
/// 设置降噪开关
- (void)sendNoiseSwitch:(BOOL)on;
/// 设置 USB 开关
- (void)sendUsbSwitch:(BOOL)on;
/// 设置开机录音
- (void)sendPowerOnRecord:(BOOL)on;
/// 设置分段录音时长（分钟）
- (void)sendSegmentDuration:(NSInteger)minutes;
/// 设置空闲关机时长（分钟）
- (void)sendIdleShutdown:(NSInteger)minutes;
/// 设置麦克风增益（1~7）
- (void)sendMicGain:(NSInteger)gain;
/// 格式化磁盘
- (void)sendFormatDisk;
/// 下载设备上的文件到本地
- (void)downloadFile:(AIRECBleFile * _Nonnull)file;
/// 取消当前下载
- (void)cancelDownload;
/// 文件是否已下载到本地
- (BOOL)isDownloaded:(NSString * _Nonnull)fileName SWIFT_WARN_UNUSED_RESULT;
/// 获取已下载文件的本地路径
- (NSString * _Nullable)getLocalPath:(NSString * _Nonnull)fileName SWIFT_WARN_UNUSED_RESULT;
@end

@class CBPeripheral;
@class CBService;
@class CBCharacteristic;
@interface AIRECBleManager (SWIFT_EXTENSION(AIRECBleKit)) <CBPeripheralDelegate>
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
@end

@class CBCentralManager;
@class NSNumber;
@interface AIRECBleManager (SWIFT_EXTENSION(AIRECBleKit)) <CBCentralManagerDelegate>
- (void)centralManagerDidUpdateState:(CBCentralManager * _Nonnull)central;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDiscoverPeripheral:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData RSSI:(NSNumber * _Nonnull)RSSI;
- (void)centralManager:(CBCentralManager * _Nonnull)central didConnectPeripheral:(CBPeripheral * _Nonnull)peripheral;
- (void)centralManager:(CBCentralManager * _Nonnull)central didFailToConnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDisconnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
@end

@protocol AIRECPlayerDelegate;
/// AIREC 多格式音频播放器（public API）
SWIFT_CLASS("_TtC11AIRECBleKit11AIRECPlayer")
@interface AIRECPlayer : NSObject
@property (nonatomic, weak) id <AIRECPlayerDelegate> _Nullable delegate;
@property (nonatomic, readonly) BOOL isPlaying;
@property (nonatomic, readonly) NSTimeInterval duration;
@property (nonatomic, readonly) NSTimeInterval currentTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)playWithFilePath:(NSString * _Nonnull)filePath;
- (void)pause;
- (void)resume;
- (void)stop;
- (void)seekTo:(NSTimeInterval)time;
- (void)clearCacheFor:(NSString * _Nonnull)filePath;
- (void)getShareablePathFor:(NSString * _Nonnull)filePath completion:(void (^ _Nonnull)(NSString * _Nullable))completion;
@end

@class AVAudioPlayer;
@interface AIRECPlayer (SWIFT_EXTENSION(AIRECBleKit)) <AVAudioPlayerDelegate>
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)p successfully:(BOOL)f;
@end

/// 播放器状态回调
SWIFT_PROTOCOL("_TtP11AIRECBleKit19AIRECPlayerDelegate_")
@protocol AIRECPlayerDelegate
@optional
- (void)playerDidStartPlaying:(AIRECPlayer * _Nonnull)player;
- (void)playerDidPause:(AIRECPlayer * _Nonnull)player;
- (void)playerDidStop:(AIRECPlayer * _Nonnull)player;
- (void)playerDidFinish:(AIRECPlayer * _Nonnull)player;
- (void)player:(AIRECPlayer * _Nonnull)player didUpdateProgress:(NSTimeInterval)currentTime duration:(NSTimeInterval)duration;
- (void)player:(AIRECPlayer * _Nonnull)player didFailWithError:(NSString * _Nonnull)error;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
